sudo: false

language: java

jdk: oraclejdk8

notifications:
  irc: "chat.freenode.net#seedstack-dev"

cache:
  directories: "$HOME/.m2/repository"

install:
  - rm ~/.m2/settings.xml
  - if [[ $TRAVIS_PULL_REQUEST = false ]] && [[ $TRAVIS_BRANCH = master ]] || [[ $TRAVIS_TAG = v* ]]; then GOAL=deploy; else GOAL=install; fi
  - if [[ $TRAVIS_TAG = v* ]]; then mvn install org.seedstack:seedstack-maven-plugin:LATEST:release; fi

script: mvn -q -U -Pbuild-number,bintray,snapshots,javadoc $GOAL
